version: '3.8'

services:
  openapi-mcp:
    build:
      context: ..
      dockerfile: Dockerfile
    image: openapi-mcp-example-demo-compose:latest
    container_name: openapi-mcp-example-demo-service

    ports:
      - "8080:8080"

    volumes:
      - ./demo:/app/example/demo

    command: >
      --spec /app/example/demo/demo-swagger.json
      --set-body createUser.user.name=ooxx
      --set-header-to-body createAdmin.admin.idToken2=headers.X-Connection-ID
      --pass-conn-id true
      --port 8080

    restart: unless-stopped